### ISSUE TITLE
rsync needs --inplace

### ISSUE THREAD

**Issue by brianjmurrell** [adlibre/adlibre-backup#14]
Don't you need to use ```rsync```'s ```--inplace``` option to get the efficiency of the snapshotting of ZFS (and I would assume btrfs)?

Otherwise when ```rsync``` detects any change of file content it rebuilds the new file in a temporary name such as ```.$filename.$unique_string``` in the same directory as the original file, pulling data from the original local file and the remote file to reconstruct the new local file.  But only once it's reconstructed in that temporary file does it then replace (probably with what is effectively a ```mv```) the original file with the new file.  But by that time you have lost the efficiency of not duplicating the identical blocks between the snapshot(s) and where the new file is being created.

**Comment by macropin** [comment]
Thanks. Good pickup. I'm surprised this was missed for so long.
