### ISSUE TITLE
backup multiple hosts at the same time

### ISSUE THREAD

**Issue by jserviceorg** [adlibre/adlibre-backup#25]
might it be possible to integrate multiple host backups at the same time? something like jobs=4 within backup.conf 

for sure this would speed up the backupjobs since rsync is not the fastest

**Comment by macropin** [comment]
I also don't have any plans to implement concurrent backup capability into `backup-runner.sh` (but if you want to send a PR with a complete/sane/portable implementation I'll likely accept it). For most of our usage rsync is very fast unless you're used with very large filesystems > 1,000,000 inodes, but for those other methods are more suitable (eg native btrfs / zfs send/receive). 

That said, if you do want to parallelize the backups there is no reason why this can't be implemented externally. The easiest way is to create two or more crontab entries, and backup a portion of the hosts with each. The only issue with parallelize the backup jobs is that the main backup log file will be intermingled.
